### ISSUE TITLE
Nit flup: ValidatedResponse

### ISSUE THREAD

**Issue by asmello** [helsing-ai/buffrs#128]
i would impl also `into_inner`, its common for wrappers

_Originally posted by @mara-schulke in https://github.com/helsing-ai/buffrs/pull/103#discussion_r1358079907_

Maybe we should replace `From<ValidatedResponse> for reqwest::Response` with an `.into_inner()` function?

**Comment by Leopard2A5** [comment]
Closed with https://github.com/helsing-ai/buffrs/pull/266
