### ISSUE TITLE
Package name has to be minimum of three characters. This seems like an arbitrary rule

### ISSUE THREAD

**Issue by joshikosuru** [helsing-ai/buffrs#156]
Is there any reason for why such rule is being enforced?

**Comment by xfbs** [comment]
I don't know for sure what the rationale here is. We should probably document it somewhere!

My best guess is: in buffrs, packages are addressed by their name. To make it useful, we want people to use semantic names — meaning that the name encodes what the package does. So, we would much prefer a package name such as `twitter_api` or `metric_temperatures`, that clearly state what they contain, over package names such as `xy` or `lot`, that leave a lot of room for guessing or interpretation.

Do you have a specific use-case where you would like to use shorter package names? Feel free to add some context, explain what you are trying to do. 

These rules are not hard and fast, we can work on them, as we understand how people are using `buffrs`. Sometimes, it might be that you are using it in a way that it was not intended for, so more information helps.

Cheers :)

**Comment by joshikosuru** [comment]
> So, we would much prefer a package name such as twitter_api or metric_temperatures, that clearly state what they contain

This makes sense.

In our use case, we define some core libraries which have package names of two characters, such as `si` for service infrastructure. Since proto, by itself doesn't have any such restrictions, I think buffrs should not enforce such restriction on package as it becomes harder for folks using other ways to manage protobuf to migrate to buffrs seamlessly,

**Comment by xfbs** [comment]
I understand, I suppose that makes sense. Maybe the rules regarding package names is something that we can either revisit, or allow for configuration. Just because this rule makes sense for us does not mean it makes sense for everyone.

Currently, we are working on building a registry. I think that long-term, we would probably move some of that validation logic into the registry. At that point, it might make sense to add some configurability there and allow overriding the default policy.

Would that solve your concern?

**Comment by mara-schulke** [comment]
I would suggest that we can just drop the constraint for now, to make it usable for you @joshikosuru 😊

**Comment by joshikosuru** [comment]
@mara-schulke Since we are currently checking how _buffrs_ work, I did comment the requirement out locally and installed _buffrs_ from local path.

I'd suggest making this change, if it makes sense that others can leverage the tool in a seamless manner.

**Comment by mara-schulke** [comment]
I have opened a PR for this, we will get it merged asap :) @joshikosuru

**Comment by mara-schulke** [comment]
fyi @joshikosuru: #158 will be part of the next patch release
