### ISSUE TITLE
Unclear error message for #192

### ISSUE THREAD

**Issue by qsantos** [helsing-ai/buffrs#193]
From #192:

```
~% git clone git@gitlab.helsing-dev.ai:infrastructure/forward.git
~% cd forward/agent
~/forward/agent% buffrs install
Error:   × failed to install dependencies for `hs-infrastructure-forward-agent`
  ╰─▶ No such file or directory (os error 2)

```

The error message does not help understanding that the issue comes from the missing `proto/vendor/` directory.

**Comment by qsantos** [comment]
The error message comes from [`src/package/store.rs`](https://github.com/helsing-ai/buffrs/blob/4a6d0e9084638f40909052aa1894bc20facbc01b/src/package/store.rs#L53):
```rust
        let meta = fs::metadata(&self.proto_path()).await.into_diagnostic()?;
```
The `core::result::Result` returned by the `Future` is converted into a `miette::Result` but no context message is attached.

Would it make sense to require that any call to `into_diagnostic()` be followed by a call to `wrap_err()`? Maybe we could make a lint for that.

**Comment by qsantos** [comment]
Note, however, that the full function is:

```rust
    /// Check if this store exists
    async fn exists(&self) -> miette::Result<bool> {
        let meta = fs::metadata(&self.proto_path()).await.into_diagnostic()?;

        Ok(meta.is_dir())
    }
```
This function will only return `Ok(false)` if the entry exists but is not a directory. In this case, maybe it would make more sense to do:
```rust
    /// Check if this store exists
    async fn exists(&self) -> bool {
        fs::metadata(&self.proto_path()).await.is_ok_and(|meta| meta.is_dir())
    }
```

**Comment by gbouv** [comment]
This seems to be fixed right? I tried to repro and now buffrs automatically create the proto/vendor directory
