### ISSUE TITLE
Detect version conflicts when code generating

### ISSUE THREAD

**Issue by asmello** [helsing-ai/buffrs#208]
Currently the generated code has implicit dependencies on a specific API version of tonic (eg, `tonic::codegen::tokio_stream::Stream`). There is no validation that the host project depends on the same tonic version, so the generated code may fail to compile.

Buffrs can and should detect this problem when running the `buffrs generate` command.

**Comment by Jolyon-S** [comment]
And for `prost` too - updating the `tonic` version resolved that issue, but it also required `prost` to be on at least the same version as `buffrs` to work.

**Comment by mara-schulke** [comment]
I would suggest that we deprecate buffrs::build + buffrs generate and provide a kickstarter `build.rs`. What do you think @asmello @Jolyon-S ?

**Comment by mara-schulke** [comment]
`buffrs::build` + `buffrs generate` have been removed in 0.8 so I would close this issue
