### ISSUE TITLE
consider gix instead of libgit2

### ISSUE THREAD

**Issue by j-baker** [helsing-ai/buffrs#217]
libgit2 is a fairly minor dependency for buffrs, but at a fairly high cost for users. git is in the default featureset, so:

1. Builds take a long time due to need to compile openssl, libgit2, etc (e.g. a cargo package using the buffrs crate will take 5 minutes to compile every time the right env vars change).
2. They can fail more easily on esoteric platforms. For example, I'm using cargo zigbuild to build python wheels, and this is complaining when trying to access zlib during the vendored openssl build. I can only assume it's gotten confused with its compilers in one place or another (maybe it's trying to use clang when it should be using gcc? not sure).

Instead of using libgit2 and all the extra cruft this entails, we could use gix instead, which I think supports the specific functionality we need. This would simplify the native dependency tree and reduce install times.

**Comment by mara-schulke** [comment]
FWIW @j-baker you can disable the git feature!

**Comment by vsiles** [comment]
I'm not familiar with these libs but that's a good way to get to know more of buffrs. I'll spend some time on it to assess if `gix` is a good substitute, and do the refactoring if that's the case. Thanks for flagging it

**Comment by vsiles** [comment]
From what I understand of the usage of git2 in buffrs, it is mostly to check if the repo is "clean" (all files are either committed or ignored).

gix and gix_status don't seem to be "there yet":
- using these crates, I managed to get information on any tracked files with non committed changes
- however I can't find how to get information about untracked files. Looking at [the project status](https://github.com/Byron/gitoxide/blob/main/crate-status.md) it seems this is not supported at the moment.

The current code would complain if some untracked files are present. We could walk the file system and check if there are some files that are not tracked and not ignored to achieve our goal, but I don't know if gix can give me information about ignored files. I'll try to check that and be back at you.

**Comment by tomkarw** [comment]
Completed in https://github.com/helsing-ai/buffrs/pull/220.
