### ISSUE TITLE
Enable users to add the latest version of a dependency through `buffrs add`

### ISSUE THREAD

**Issue by mara-schulke** [helsing-ai/buffrs#223]
It would be greatly improving the user experience to be able to add a dependency using `latest` instead of a fixed version string and having buffrs figure out what the latest version is!

e.g. `buffrs add --registry <registry> some-repo/some-package@latest`

**Comment by tomkarw** [comment]
How about the syntax being just skipping the version:
```
buffrs add --registry <registry> some-repo/some-package
```
Like `cargo add <some-package>` for example.
