### ISSUE TITLE
Missing `generate` ?

### ISSUE THREAD

**Issue by dgehriger** [helsing-ai/buffrs#254]
@mara-schulke 

According to the book, one can use `buffrs generate` and

```rust
    buffrs::generate().unwrap();
```

But the latest version doesn't have such a command anymore. Furthermore, the `build` feature isn't available. Is Rust code generation now out of scope for buffrs?

And related: how do we express in buffrs that a service implements a well-known API, such as the [gRPC Health Service](https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto) ?

**Comment by mara-schulke** [comment]
Hi @dgehriger, yes, im sorry this is outdated. This must be removed from the docs, I'll try to find some time for this.

As for the last question: We don't. Buffrs doesnt track any implementations, only the raw protos!

**Comment by dgehriger** [comment]
> Hi @dgehriger, yes, im sorry this is outdated. This must be removed from the docs, I'll try to find some time for this.
> 
> 
> 
> As for the last question: We don't. Buffrs doesnt track any implementations, only the raw protos!

Thanks for your answer. Can you just elaborate how you typically generate the protos managed by buffrs now?

**Comment by mara-schulke** [comment]
@dgehriger yes of course:

We usually default back to language native build tooling. A good example in the rust world would be the `tonic_build` & `prost` crates. For TS I believe there is a `protobuf-ts` npm package.

Buffrs takes care of _moving the protos_, language specific tooling takes care of _compiling them into stubs_.

**Comment by mara-schulke** [comment]
I believe the docs are now repaired as per #255 😊
