### ISSUE TITLE
Cache is not populated on first install

### ISSUE THREAD

**Issue by fredrb** [helsing-ai/buffrs#258]
Seems like cache is only persisted if the dependency is already in the lock file.

Here's how I reproduced the issue:

1. Clean current buffrs cache (if any)
```
$ rm ~/.buffrs/cache/*
```
2. In a fresh buffrs project (already initialized) add first dependency
3. Run `buffrs install`
4. Check cache contents:
```
$ ls -la ~/.buffrs/cache
total 0
drwxr-xr-x  2 user  staff   64 Jul  5 10:30 .
drwxr-xr-x  4 user  staff  128 Jul  4 10:45 ..
```
5. Remove proto files from project but keep `Proto.lock` file
```
$ rm -rf ./proto
```
6. Run `buffrs install` again
7. Check that now cache has the installed proto packages
```
$ ls -la ~/.buffrs/cache
total 24
drwxr-xr-x  5 user  staff  160 Jul  5 10:31 .
drwxr-xr-x  4 user  staff  128 Jul  4 10:45 ..
-rw-r--r--@ 1 user  staff  341 Jul  5 10:31 my-proto.sha256.8d164e99fef50adc9737550c39c859be3ab6e4a1a81f74e4709a37461e912c59.tgz
```

**Comment by mara-schulke** [comment]
Would you be interested in fixing this? This is definitely unintended behavior! Thank you for raising! 😊

**Comment by fredrb** [comment]
@mara-schulke will do!
