### ISSUE TITLE
Work on python + js build tool support

### ISSUE THREAD

**Issue by mara-schulke** [helsing-ai/buffrs#27]

**Comment by mara-schulke** [comment]
For vite we can use plugins:

https://github.com/vitejs/awesome-vite#framework-agnostic-plugins

We should also provide a next.js plugin and think about typescript support!

---

Python looks like it will be relying on Kraken for now.

**Comment by mara-schulke** [comment]
@alexespencer is taking a look at the python integration soon

**Comment by alexespencer** [comment]
https://github.com/helsing-ai/buffrs/pull/72 This PR added python code generation via `buffrs generate --lang python --out-dir <OUTPUT_DIRECTORY>`

I would suggest `js` support is a good first issue and that this is picked up by somebody else.

Kraken integration is tracked here: https://github.com/kraken-build/kraken-build/pull/120

**Comment by asmello** [comment]
Let's close this out and break out a separate issue for JS.
