### ISSUE TITLE
 lockfile

### ISSUE THREAD

**Issue by j-baker** [helsing-ai/buffrs#3]
Internally am trying to incrementally ensure our ecosystem is as nix-buildable as possible. One of the constraints imposed by Nix is that derivations should be immutable - every call must return the same value. This is valuable for obvious reasons, and Nix reasonably doesn't trust that URLs can't change.

When integrating an external package manager (like Cargo, or buffrs) into Nix, this typically means that the integration occurs along the lines of the package manager's lockfile - the config+lockfile together contain enough information to reconstruct a URL and a cryptographic hash of that content.

It would be convenient if buffrs utilised a similar lockfile, which could be e.g. updated at generation time like Cargo.lock. This would have the additional benefit of detecting any accidental overwrites, and while internally we'll usually use Artifactory with a config which disallows these, I'd expect that the mooted S3 integration would benefit from it.

**Comment by mara214** [comment]
I agree! Thanks for suggesting this! 😊 
I'll start to implement this this week or next week

**Comment by mara214** [comment]
We should also store the buffrs / protoc version in the lockfile to detect problems in codegen early on!

**Comment by j-baker** [comment]
Is there an ETA on this?

**Comment by mara214** [comment]
Starting September we have additional resources on buffrs to tackle this so I assume 1-3 weeks - is that okay or do you need it earlier?

**Comment by mara-schulke** [comment]
#38 is drafting the implementation for this 😊 

LMK if you have ideas regarding the implementation / feel free to take a look at the pr 

--

Is there any special contract the lockfile has to fulfill to be meaningful for the nix integration?

So far we pin these values for each installed package:

- Version
- Name
- Artifactory Repository
- Checksum
- Dependencies of the Package

**Comment by mara-schulke** [comment]
Lockfiles landed @j-baker!
