### ISSUE TITLE
Make packages deterministic

### ISSUE THREAD

**Issue by asmello** [helsing-ai/buffrs#50]
Currently it appears the generated tar packages are sensitive to filesystem metadata (particularly last access timestamps etc.), which means two packages built in two different computers might have a different checksum even if the actual contents are identical.

In order to make building and publishing a reproducible process (which should pave the way for better testing and supply chain security), generating the tar packages should be a deterministic process which depends only on the protobuf definitions.

**Comment by mara-schulke** [comment]
Good idea!

**Comment by mara-schulke** [comment]
Slightly related nit: When we compare binary files we should use checksums instead of the string comp

**Comment by asmello** [comment]
Checksum comparison is great for many-to-many matching, but since we're comparing files directly 1:1, isn't it simpler to just do a byte-wise comparison?

**Comment by mara-schulke** [comment]
Yes but its hard to replicate on the terminal – you can get a sha of a file quite easily

I would at least propose to print a sha mismatch so people can debug manually easier

Getting the error "your test failed because the byte at position xyz is not bar" is less helpful to the person debugging?
