### ISSUE TITLE
Buffrs install gives a bad error message

### ISSUE THREAD

**Issue by mara-schulke** [helsing-ai/buffrs#75]
```
λ buffrs install
Error:
   0: Server response has incorrect mime type: "application/json;charset=ISO-8859-1"

Location:
   src/registry/artifactory.rs:154

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

this happened after updating from buffrs v0.5 (with old credentials present) to buffrs v0.6

**Comment by mara-schulke** [comment]
Im guessing this is due to non present credentials -> jfrog returns a json with an error message and our mimetype validation fails.

**Comment by mara-schulke** [comment]
Running a clean buffrs install fixed it

**Comment by asmello** [comment]
I can't reproduce this by generating a credentials.toml file with v0.5.0 and then invoking install with v0.6.0.

**Comment by asmello** [comment]
Actually I managed to reproduce later yesterday, will prepare a fix today.
